{
  "hash": "ed15d1de721670d12aa0f0adce8a84e8",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\n# Assignment\n\n------------------------------------------------------------------------\n\n### Task 1:\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_2c6d8e70f2c1cdce9e24863e94eb20ce'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dagitty)\nlibrary(ggdag)\nlibrary(ggplot2)\n\ndag <- 'dag {\n  Parking [exposure,pos=\"0.1,0.5\"]\n  Sales [outcome,pos=\"0.5,0.5\"]\n  Location [pos=\"0.3,1\"]\n  Parking -> Sales\n  Location -> Parking\n  Location -> Sales\n}'\nggdag_status(dag) +\ntheme_dag() +\ntheme(plot.background = element_rect(fill = \"lightblue\"))\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n### Task 2:\n\n> Loading the customer_sat data set\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_535f04ac6199e0da2da2fa285a687bcb'}\n\n```{.r .cell-code}\ndf_customer_sat <- readRDS(\"../../Causal_Data_Science_Data/customer_sat.rds\")\nhead(df_customer_sat)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"follow_ups\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"satisfaction\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"subscription\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"8\",\"2\":\"40\",\"3\":\"Elite\"},{\"1\":\"7\",\"2\":\"45\",\"3\":\"Elite\"},{\"1\":\"8\",\"2\":\"47\",\"3\":\"Elite\"},{\"1\":\"9\",\"2\":\"44\",\"3\":\"Elite\"},{\"1\":\"10\",\"2\":\"50\",\"3\":\"Elite\"},{\"1\":\"6\",\"2\":\"55\",\"3\":\"Premium+\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### 1.   Regress `satisfaction` on `follow_ups`\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_0c2c1b94fc28828c9eb68b4356159622'}\n\n```{.r .cell-code}\nlm_model1 <- lm(satisfaction ~ follow_ups, data = df_customer_sat)\n```\n:::\n\n> Summary\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_2b2a6a08bd4809172547041ff501e394'}\n\n```{.r .cell-code}\nsummary(lm_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = df_customer_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n:::\n\n\n#### 2.   Regress `satisfaction` on `follow_ups` and account for `subscription`\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-5_5202063852d81b70142919bd455b75d3'}\n\n```{.r .cell-code}\nlm_model_2 <- lm(satisfaction ~ follow_ups + subscription, data = df_customer_sat)\n```\n:::\n\n> Summary\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-6_ef94649dadcf515f5974f8b97fd9aef1'}\n\n```{.r .cell-code}\nsummary(lm_model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = df_customer_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n\n\n### Task 3:\n\n* Common Predictors:\n\n  + Both models include an intercept and the predictor variable follow_ups.\n  + The coefficient for follow_ups is negative in Model 1 and positive in Model 2.\n\n* Additional Predictors in Model 2:\n\n + Model 2 includes two additional predictor variables: subscriptionPremium and subscriptionPremium+.\n + These variables have positive coefficients, indicating a positive impact on the dependent variable.\n\n* Possible Explanation:\n\n  + The introduction of subscription-related predictors (subscriptionPremium and subscriptionPremium+) in Model 2 might be associated with a change in the business strategy or customer segmentation.\n  + The positive coefficients for subscription-related predictors in Model 2 suggest that having a premium subscription or a premium+ subscription is associated with higher values of the dependent variable.\n\n* Overall Model Performance:\n\n  + Model 2 has a higher adjusted R-squared (0.9487) compared to Model 1 (0.6316), indicating that the predictors in Model 2 explain a larger proportion of the variance in the dependent variable.\n\n* Statistical Significance:\n\n  + All coefficients in Model 2, including the intercept, follow_ups, and subscription-related predictors, are statistically significant.\n  \n::: callout-note\nIn summary, the differences in coefficients between the two models can be attributed to the introduction of new predictors related to subscription types in Model 2. The positive coefficients for subscription-related predictors suggest that these subscriptions contribute significantly to the higher values of the dependent variable in the presence of follow-ups.\n:::\n\n### Task 4\n\n> Without Conditioning on Subscription\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-7_72a97d675cdba1f75740a26c266d92ff'}\n\n```{.r .cell-code}\nsimps_not_cond  <- ggplot(df_customer_sat, aes(x = follow_ups, y = satisfaction)) +\n  geom_point(alpha = .8) +\n  stat_smooth(method = \"lm\", se = F)\n\nsimps_not_cond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n> Conditioning on Subscription\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-8_f28cc8d35d5f0d5e0676057bcaa5c642'}\n\n```{.r .cell-code}\nsimps_cond <- ggplot(df_customer_sat, aes(x = follow_ups, y = satisfaction, color = subscription )) +\n  geom_point(alpha = .8) +\n  stat_smooth(method = \"lm\", se = F) +\n  theme(legend.position = \"right\")\n\nsimps_cond \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}