{
  "hash": "7180e3c191cac392a047b66a0131fafb",
  "result": {
    "markdown": "---\ntitle: \"Regression and Statistical Inference\"\n---\n\n\n# Assignment\n\n------------------------------------------------\n\n### Task 1:\n\nReading the data for its dimensions,\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-1_15019203e8796ce4a2b72fee743eb5e5'}\n\n```{.r .cell-code}\n# Loading the file car_prices\ndf_car_prices <- readRDS(\"../../Causal_Data_Science_Data/car_prices.rds\")\n# Dimensions of the data\ndim(df_car_prices)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 181  22\n```\n:::\n:::\n\nThe data has `181 rows` and `22 columns`.\n\n### Task 2:\n\n> Detailed look of the data\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-2_3c769119466aa0e6d0924625eaedd743'}\n\n```{.r .cell-code}\nt(summary(df_car_prices))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>                                                                          \n#>  aspiration      Length:181         Class :character   Mode  :character  \n#>  doornumber      Length:181         Class :character   Mode  :character  \n#>   carbody        Length:181         Class :character   Mode  :character  \n#>  drivewheel      Length:181         Class :character   Mode  :character  \n#> enginelocation   Length:181         Class :character   Mode  :character  \n#>   wheelbase      Min.   : 86.60     1st Qu.: 94.50     Median : 96.50    \n#>   carlength      Min.   :141.1      1st Qu.:166.3      Median :173.0     \n#>    carwidth      Min.   :60.30      1st Qu.:64.00      Median :65.40     \n#>   carheight      Min.   :47.80      1st Qu.:52.00      Median :53.70     \n#>   curbweight     Min.   :1488       1st Qu.:2122       Median :2410      \n#>  enginetype      Length:181         Class :character   Mode  :character  \n#> cylindernumber   Length:181         Class :character   Mode  :character  \n#>   enginesize     Min.   : 61.0      1st Qu.: 98.0      Median :120.0     \n#>  fuelsystem      Length:181         Class :character   Mode  :character  \n#>   boreratio      Min.   :2.540      1st Qu.:3.150      Median :3.310     \n#>     stroke       Min.   :2.07       1st Qu.:3.08       Median :3.23      \n#> compressionratio Min.   : 7.000     1st Qu.: 8.500     Median : 9.000    \n#>   horsepower     Min.   : 48.0      1st Qu.: 70.0      Median : 95.0     \n#>    peakrpm       Min.   :4200       1st Qu.:4800       Median :5200      \n#>    citympg       Min.   :13.00      1st Qu.:19.00      Median :24.00     \n#>   highwaympg     Min.   :16.00      1st Qu.:25.00      Median :30.00     \n#>     price        Min.   : 5118      1st Qu.: 7609      Median : 9980     \n#>                                                                    \n#>  aspiration                                                        \n#>  doornumber                                                        \n#>   carbody                                                          \n#>  drivewheel                                                        \n#> enginelocation                                                     \n#>   wheelbase      Mean   : 98.21   3rd Qu.:100.40   Max.   :120.90  \n#>   carlength      Mean   :173.3    3rd Qu.:180.2    Max.   :208.1   \n#>    carwidth      Mean   :65.74    3rd Qu.:66.50    Max.   :72.30   \n#>   carheight      Mean   :53.58    3rd Qu.:55.50    Max.   :59.80   \n#>   curbweight     Mean   :2521     3rd Qu.:2910     Max.   :4066    \n#>  enginetype                                                        \n#> cylindernumber                                                     \n#>   enginesize     Mean   :127.1    3rd Qu.:141.0    Max.   :326.0   \n#>  fuelsystem                                                        \n#>   boreratio      Mean   :3.325    3rd Qu.:3.590    Max.   :3.940   \n#>     stroke       Mean   :3.23     3rd Qu.:3.40     Max.   :4.17    \n#> compressionratio Mean   : 8.848   3rd Qu.: 9.400   Max.   :11.500  \n#>   horsepower     Mean   :106.2    3rd Qu.:116.0    Max.   :288.0   \n#>    peakrpm       Mean   :5182     3rd Qu.:5500     Max.   :6600    \n#>    citympg       Mean   :24.85    3rd Qu.:30.00    Max.   :49.00   \n#>   highwaympg     Mean   :30.48    3rd Qu.:34.00    Max.   :54.00   \n#>     price        Mean   :12999    3rd Qu.:16430    Max.   :45400\n```\n:::\n:::\n\n\n>Correlation of numerical columns\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-3_62e7dd9a6db53f6008102e58708d1fe6'}\n\n```{.r .cell-code}\n# Selecting only numeric columns\nnumeric_cols <- df_car_prices[sapply(df_car_prices, is.numeric)]\n\n# Calculating correlation matrix\ncor(numeric_cols)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>                    wheelbase   carlength   carwidth   carheight curbweight\n#> wheelbase         1.00000000  0.86117385  0.7697984  0.54019069  0.7367123\n#> carlength         0.86117385  1.00000000  0.8264703  0.44081316  0.8660053\n#> carwidth          0.76979836  0.82647026  1.0000000  0.20488138  0.8480000\n#> carheight         0.54019069  0.44081316  0.2048814  1.00000000  0.2141918\n#> curbweight        0.73671231  0.86600528  0.8480000  0.21419176  1.0000000\n#> enginesize        0.55411851  0.68017071  0.7431094 -0.02315796  0.8664640\n#> boreratio         0.46436865  0.60094354  0.5515756  0.13853090  0.6382900\n#> stroke            0.07182428  0.06571525  0.1143203 -0.15074728  0.1003967\n#> compressionratio -0.25528942 -0.25098987 -0.2497246 -0.04784995 -0.3108351\n#> horsepower        0.40436893  0.59890956  0.6971702 -0.09471443  0.8176250\n#> peakrpm          -0.21992786 -0.19115857 -0.1086424 -0.15338356 -0.1596062\n#> citympg          -0.58337119 -0.78122590 -0.7392601 -0.15044099 -0.8727123\n#> highwaympg       -0.62686055 -0.78886402 -0.7501573 -0.18342575 -0.8873144\n#> price             0.55547499  0.67307358  0.7430132  0.07452058  0.8340814\n#>                   enginesize  boreratio      stroke compressionratio\n#> wheelbase         0.55411851  0.4643687  0.07182428      -0.25528942\n#> carlength         0.68017071  0.6009435  0.06571525      -0.25098987\n#> carwidth          0.74310940  0.5515756  0.11432033      -0.24972464\n#> carheight        -0.02315796  0.1385309 -0.15074728      -0.04784995\n#> curbweight        0.86646404  0.6382900  0.10039673      -0.31083510\n#> enginesize        1.00000000  0.5779073  0.18198111      -0.16132409\n#> boreratio         0.57790729  1.0000000 -0.10077211      -0.19600019\n#> stroke            0.18198111 -0.1007721  1.00000000      -0.30056815\n#> compressionratio -0.16132409 -0.1960002 -0.30056815       1.00000000\n#> horsepower        0.84661455  0.5917398  0.11169001      -0.22352509\n#> peakrpm          -0.18477648 -0.2363817  0.06779511       0.15590249\n#> citympg          -0.74373969 -0.6185363 -0.09158746       0.43789655\n#> highwaympg       -0.75541425 -0.6086412 -0.07422008       0.44866322\n#> price             0.88970342  0.5540692  0.03082326      -0.17646152\n#>                   horsepower     peakrpm     citympg  highwaympg       price\n#> wheelbase         0.40436893 -0.21992786 -0.58337119 -0.62686055  0.55547499\n#> carlength         0.59890956 -0.19115857 -0.78122590 -0.78886402  0.67307358\n#> carwidth          0.69717017 -0.10864244 -0.73926008 -0.75015733  0.74301316\n#> carheight        -0.09471443 -0.15338356 -0.15044099 -0.18342575  0.07452058\n#> curbweight        0.81762499 -0.15960618 -0.87271235 -0.88731441  0.83408139\n#> enginesize        0.84661455 -0.18477648 -0.74373969 -0.75541425  0.88970342\n#> boreratio         0.59173978 -0.23638175 -0.61853627 -0.60864116  0.55406923\n#> stroke            0.11169001  0.06779511 -0.09158746 -0.07422008  0.03082326\n#> compressionratio -0.22352509  0.15590249  0.43789655  0.44866322 -0.17646152\n#> horsepower        1.00000000  0.08277528 -0.80612428 -0.77717065  0.84009827\n#> peakrpm           0.08277528  1.00000000  0.02610522  0.05111792 -0.02085359\n#> citympg          -0.80612428  0.02610522  1.00000000  0.97537685 -0.74198802\n#> highwaympg       -0.77717065  0.05111792  0.97537685  1.00000000 -0.74079733\n#> price             0.84009827 -0.02085359 -0.74198802 -0.74079733  1.00000000\n```\n:::\n:::\n\n\n> Data types of each column and the samples \n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-4_74b5548a9288ce366c86a292a86ed09c'}\n\n```{.r .cell-code}\n# Data Types\nstr(df_car_prices)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> tibble [181 × 22] (S3: tbl_df/tbl/data.frame)\n#>  $ aspiration      : chr [1:181] \"std\" \"std\" \"std\" \"std\" ...\n#>  $ doornumber      : chr [1:181] \"two\" \"two\" \"two\" \"four\" ...\n#>  $ carbody         : chr [1:181] \"convertible\" \"convertible\" \"hatchback\" \"sedan\" ...\n#>  $ drivewheel      : chr [1:181] \"rwd\" \"rwd\" \"rwd\" \"fwd\" ...\n#>  $ enginelocation  : chr [1:181] \"front\" \"front\" \"front\" \"front\" ...\n#>  $ wheelbase       : num [1:181] 88.6 88.6 94.5 99.8 99.4 ...\n#>  $ carlength       : num [1:181] 169 169 171 177 177 ...\n#>  $ carwidth        : num [1:181] 64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...\n#>  $ carheight       : num [1:181] 48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...\n#>  $ curbweight      : num [1:181] 2548 2548 2823 2337 2824 ...\n#>  $ enginetype      : chr [1:181] \"dohc\" \"dohc\" \"ohcv\" \"ohc\" ...\n#>  $ cylindernumber  : chr [1:181] \"four\" \"four\" \"six\" \"four\" ...\n#>  $ enginesize      : num [1:181] 130 130 152 109 136 136 136 136 131 131 ...\n#>  $ fuelsystem      : chr [1:181] \"mpfi\" \"mpfi\" \"mpfi\" \"mpfi\" ...\n#>  $ boreratio       : num [1:181] 3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...\n#>  $ stroke          : num [1:181] 2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...\n#>  $ compressionratio: num [1:181] 9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...\n#>  $ horsepower      : num [1:181] 111 111 154 102 115 110 110 110 140 160 ...\n#>  $ peakrpm         : num [1:181] 5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...\n#>  $ citympg         : num [1:181] 21 21 19 24 18 19 19 19 17 16 ...\n#>  $ highwaympg      : num [1:181] 27 27 26 30 22 25 25 25 20 22 ...\n#>  $ price           : num [1:181] 13495 16500 16500 13950 17450 ...\n```\n:::\n:::\n\nTotal unique data types in the car_price data set\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-5_461d3f9ae0b7947e808c0a983444448a'}\n\n```{.r .cell-code}\n# Seeing the datatypes in the data\ncolumn_types <- sapply(df_car_prices, class)\n# Get unique data types\nunique_types <- unique(column_types)\n# Print the unique data types\nprint(unique_types)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"character\" \"numeric\"\n```\n:::\n:::\n\n\nThere are 2 types of data types in the : character and numeric.\n\nThe `numeric` data type include both *integers and decimals* whereas `character` data types represent *text or strings*.\n\n### Task 3:\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-6_41b4d4196370c288c1a3510b948d2bee'}\n\n```{.r .cell-code}\nlm_model <- lm(price ~ ., data = df_car_prices)\nsummary(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ ., data = df_car_prices)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#>  -5662  -1120      0    798   9040 \n#> \n#> Coefficients:\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)          -36269.965  15460.866  -2.346 0.020354 *  \n#> aspirationturbo        1846.206   1041.391   1.773 0.078386 .  \n#> doornumbertwo           242.523    571.929   0.424 0.672172    \n#> carbodyhardtop        -3691.743   1424.825  -2.591 0.010561 *  \n#> carbodyhatchback      -3344.335   1238.359  -2.701 0.007757 ** \n#> carbodysedan          -2292.820   1356.014  -1.691 0.093043 .  \n#> carbodywagon          -3427.921   1490.285  -2.300 0.022885 *  \n#> drivewheelfwd          -504.564   1076.623  -0.469 0.640030    \n#> drivewheelrwd           -15.446   1268.070  -0.012 0.990299    \n#> enginelocationrear     6643.492   2572.275   2.583 0.010806 *  \n#> wheelbase               -30.197     92.776  -0.325 0.745294    \n#> carlength               -29.740     51.672  -0.576 0.565824    \n#> carwidth                731.819    244.533   2.993 0.003258 ** \n#> carheight               123.195    134.607   0.915 0.361617    \n#> curbweight                2.612      1.781   1.467 0.144706    \n#> enginetypedohcv       -8541.957   4749.685  -1.798 0.074219 .  \n#> enginetypel             978.748   1786.384   0.548 0.584619    \n#> enginetypeohc          3345.252    933.001   3.585 0.000461 ***\n#> enginetypeohcf          972.919   1625.631   0.598 0.550462    \n#> enginetypeohcv        -6222.322   1236.415  -5.033 1.43e-06 ***\n#> cylindernumberfive   -11724.540   3019.192  -3.883 0.000157 ***\n#> cylindernumberfour   -11549.326   3177.177  -3.635 0.000387 ***\n#> cylindernumbersix     -7151.398   2247.230  -3.182 0.001793 ** \n#> cylindernumberthree   -4318.929   4688.833  -0.921 0.358545    \n#> cylindernumbertwelve -11122.209   4196.494  -2.650 0.008946 ** \n#> enginesize              125.934     26.541   4.745 5.00e-06 ***\n#> fuelsystem2bbl          177.136    883.615   0.200 0.841400    \n#> fuelsystemmfi         -3041.018   2576.996  -1.180 0.239934    \n#> fuelsystemmpfi          359.278   1001.529   0.359 0.720326    \n#> fuelsystemspdi        -2543.890   1363.546  -1.866 0.064140 .  \n#> fuelsystemspfi          514.766   2499.229   0.206 0.837107    \n#> boreratio             -1306.740   1642.221  -0.796 0.427516    \n#> stroke                -4527.137    922.732  -4.906 2.49e-06 ***\n#> compressionratio       -737.901    555.960  -1.327 0.186539    \n#> horsepower               10.293     22.709   0.453 0.651035    \n#> peakrpm                   2.526      0.634   3.983 0.000108 ***\n#> citympg                 -90.352    166.647  -0.542 0.588538    \n#> highwaympg              154.858    167.148   0.926 0.355761    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2189 on 143 degrees of freedom\n#> Multiple R-squared:  0.9415,\tAdjusted R-squared:  0.9264 \n#> F-statistic: 62.21 on 37 and 143 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe significance of the parameters impacting the car price is denoted by the number of asterisks (*). The statistical significance for the mentioned columns is exceptionally low, indicating a high level of significance.\n\n* *enginetypeohc*\n\n* *enginetypeohcv*\n\n* *cylindernumberfive*\n\n* *cylindernumberfour*\n\n* *enginesize*\n\n* *stroke*\n\n* *peakrpm*\n\n### Task 4:\n\nChoice of the Regressor: `enginesize`\n\n* *Data type*: As observed in the linear regression summary, the `enginesize` variable is of `numeric` data type, accommodating both integer and decimal values. In this data set, it is notable for having integer values such as 130 152 109, etc.\n\n* *Effect on Price:* The coefficient of the `enginesiz` is 125.934. This value indicates that for each unit increase in size, the price is expected to increase by 125.934 units, keeping other variable constants.\n\n* *Statistical Significance*: The p-value for `enginesize`, which stands at `5 × 10^-6^`, is notably small. This suggests a high level of significance, indicating a substantial effect on the Price.\n\n\n### Task 5:\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-7_b8a152edc778dc836307128825e172a1'}\n\n```{.r .cell-code}\nlibrary(dplyr)\ndf_car_prices_upd <- mutate(df_car_prices, seat_heating = TRUE)\nlm_model_sh <- lm(price ~ . + seat_heating, data = df_car_prices_upd)\n```\n:::\n\n\n> Summary of the new model to see the coefficient of 'seat_heating'\n\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-8_aec85e71e9224ede8ca83b273adb7f8d'}\n\n```{.r .cell-code}\nsummary(lm_model_sh)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ . + seat_heating, data = df_car_prices_upd)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#>  -5662  -1120      0    798   9040 \n#> \n#> Coefficients: (1 not defined because of singularities)\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)          -36269.965  15460.866  -2.346 0.020354 *  \n#> aspirationturbo        1846.206   1041.391   1.773 0.078386 .  \n#> doornumbertwo           242.523    571.929   0.424 0.672172    \n#> carbodyhardtop        -3691.743   1424.825  -2.591 0.010561 *  \n#> carbodyhatchback      -3344.335   1238.359  -2.701 0.007757 ** \n#> carbodysedan          -2292.820   1356.014  -1.691 0.093043 .  \n#> carbodywagon          -3427.921   1490.285  -2.300 0.022885 *  \n#> drivewheelfwd          -504.564   1076.623  -0.469 0.640030    \n#> drivewheelrwd           -15.446   1268.070  -0.012 0.990299    \n#> enginelocationrear     6643.492   2572.275   2.583 0.010806 *  \n#> wheelbase               -30.197     92.776  -0.325 0.745294    \n#> carlength               -29.740     51.672  -0.576 0.565824    \n#> carwidth                731.819    244.533   2.993 0.003258 ** \n#> carheight               123.195    134.607   0.915 0.361617    \n#> curbweight                2.612      1.781   1.467 0.144706    \n#> enginetypedohcv       -8541.957   4749.685  -1.798 0.074219 .  \n#> enginetypel             978.748   1786.384   0.548 0.584619    \n#> enginetypeohc          3345.252    933.001   3.585 0.000461 ***\n#> enginetypeohcf          972.919   1625.631   0.598 0.550462    \n#> enginetypeohcv        -6222.322   1236.415  -5.033 1.43e-06 ***\n#> cylindernumberfive   -11724.540   3019.192  -3.883 0.000157 ***\n#> cylindernumberfour   -11549.326   3177.177  -3.635 0.000387 ***\n#> cylindernumbersix     -7151.398   2247.230  -3.182 0.001793 ** \n#> cylindernumberthree   -4318.929   4688.833  -0.921 0.358545    \n#> cylindernumbertwelve -11122.209   4196.494  -2.650 0.008946 ** \n#> enginesize              125.934     26.541   4.745 5.00e-06 ***\n#> fuelsystem2bbl          177.136    883.615   0.200 0.841400    \n#> fuelsystemmfi         -3041.018   2576.996  -1.180 0.239934    \n#> fuelsystemmpfi          359.278   1001.529   0.359 0.720326    \n#> fuelsystemspdi        -2543.890   1363.546  -1.866 0.064140 .  \n#> fuelsystemspfi          514.766   2499.229   0.206 0.837107    \n#> boreratio             -1306.740   1642.221  -0.796 0.427516    \n#> stroke                -4527.137    922.732  -4.906 2.49e-06 ***\n#> compressionratio       -737.901    555.960  -1.327 0.186539    \n#> horsepower               10.293     22.709   0.453 0.651035    \n#> peakrpm                   2.526      0.634   3.983 0.000108 ***\n#> citympg                 -90.352    166.647  -0.542 0.588538    \n#> highwaympg              154.858    167.148   0.926 0.355761    \n#> seat_heatingTRUE             NA         NA      NA       NA    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2189 on 143 degrees of freedom\n#> Multiple R-squared:  0.9415,\tAdjusted R-squared:  0.9264 \n#> F-statistic: 62.21 on 37 and 143 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nFrom the table, it's evident that the variable seat_heating exhibits no significant impact on the price. The regression model fails to establish any correlation between the price and seat_heating, resulting in a coefficient marked as NA (Not Available). This absence of correlation may be attributed to the phenomenon known as `Multi-Collinearity`. In this case, the seat_heating variable is consistently set to `True` without any variation, rendering the model incapable of estimating a coefficient for it.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}